In [1]:
pip install requests beautifulsoup4

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
URL ="https://www.timeanddate.com/weather/?low=c"
webPage=requests.get(URL).text

In [4]:
from decorator import append
soup=BeautifulSoup(webPage,'lxml')
cities=soup.find_all('tr')
name=[]
dayTime=[]
temperature=[]
for i in cities:
  links=i.find_all('a')
  for link in links:
    name.append(link.text)
  DayTimeCell=i.find_all('td',class_='r')
  for day in DayTimeCell:
    if day.text=="":
      continue
    else:
      dayTime.append(day.text)
  temp=i.find_all('td',class_='rbi')
  for t in temp:
    temperature.append(t.text)

In [5]:
print(len(name))
print(len(dayTime))
print(len(temperature))

185
185
185

In [6]:
d={'Cities':name,'DayTime':dayTime,'Temperature':temperature}
df=pd.DataFrame(d)
df

          Cities    DayTime Temperature
0          Accra  Wed 16:02       31 °C
1         Manila  Thu 00:02       29 °C
2    Addis Ababa  Wed 19:02       22 °C
3         Maputo  Wed 18:02       29 °C
4        Algiers  Wed 17:02       16 °C
..           ...        ...         ...
180         Male  Wed 21:02       31 °C
181      Yaoundé  Wed 17:02       30 °C
182      Managua  Wed 10:02       29 °C
183       Zagreb  Wed 17:02       18 °C
184       Manama  Wed 19:02       23 °C

[185 rows x 3 columns]

In [7]:
df = df.sort_values(by='Cities').reset_index(drop=True)

In [8]:
df[df['Cities']=='Islamabad']

       Cities    DayTime Temperature
67  Islamabad  Wed 21:02       24 °C