In [1]:
pip install requests beautifulsoup4

Requirement already satisfied: requests in c:\users\pmls\appdata\roaming\python\python313\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\pmls\appdata\roaming\python\python313\site-packages (4.13.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pmls\appdata\roaming\python\python313\site-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pmls\appdata\roaming\python\python313\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pmls\appdata\roaming\python\python313\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pmls\appdata\roaming\python\python313\site-packages (from requests) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\pmls\appdata\roaming\python\python313\site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\pmls\appdata\roaming\python\python313\site-packages (from beautifulsoup4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
URL ="https://www.timeanddate.com/weather/?low=c"
webPage=requests.get(URL).text

In [4]:
from decorator import append
soup=BeautifulSoup(webPage,'lxml')
cities=soup.find_all('tr')
name=[]
dayTime=[]
temperature=[]
for i in cities:
  links=i.find_all('a')
  for link in links:
    name.append(link.text)
  DayTimeCell=i.find_all('td',class_='r')
  for day in DayTimeCell:
    if day.text=="":
      continue
    else:
      dayTime.append(day.text)
  temp=i.find_all('td',class_='rbi')
  for t in temp:
    temperature.append(t.text)

In [5]:
print(len(name))
print(len(dayTime))
print(len(temperature))

181
181
181

In [6]:
d={'Cities':name,'DayTime':dayTime,'Temperature':temperature}
df=pd.DataFrame(d)
df

          Cities    DayTime Temperature
0          Accra  Thu 01:27       27 °C
1         Manila  Thu 09:27       26 °C
2    Addis Ababa  Thu 04:27       22 °C
3         Maputo  Thu 03:27       25 °C
4        Algiers  Thu 02:27       15 °C
..           ...        ...         ...
176         Male  Thu 06:27       28 °C
177      Yaoundé  Thu 02:27       23 °C
178      Managua  Wed 19:27       31 °C
179       Zagreb  Thu 02:27        7 °C
180       Manama  Thu 04:27       21 °C

[181 rows x 3 columns]

In [7]:
df = df.sort_values(by='Cities').reset_index(drop=True)

In [9]:
df[df['Cities']=='Islamabad']

       Cities    DayTime Temperature
65  Islamabad  Thu 06:27       16 °C

In [10]:
df = df.to_csv("data/file.csv",index=False)

OSError: Cannot save file into a non-existent directory: 'data'